
server:
  port: 8081

node:
  auth:
    token: dummy

spring:
  application:
    name: blockchain-node
logging:
  file: logs/${spring.application.name}.log

notary:
  transaction:
    url: http://localhost:8082/v1/initTransaction
