
server:
  port: 8081

spring:
  application:
    name: blockchain-node
logging:
  file: logs/${spring.application.name}.log

notary:
  transaction:
    url: http://localhost:8075/v1/initializeTransaction
  validateMining:
    url: http://localhost:8075/v1/validateMiningRequest
  miningRequest:
    url: http://localhost:8075/v1/miningRequest
